### PR TITLE
[FIX] Fixing method name on product_unique_serial module

### PR DESCRIPTION
**Pull request by hbto**
Changing method name from unicity, meaning one, a whole element, to uniqueness, meaning unique, only one of a kind.

### CODE REVIEW

**Comment by hbto** [comment]
> s/inicity/uniqueness/g
> 
> s/_check_inicity_lot_product/_check_uniqueness_lot/g

@nhomar 

This PR is taking care of your suggestion at https://github.com/Vauxoo/stock-logistics-workflow/pull/14

**Comment by nhomar** [comment]
in 2 PR now this has conflict for the name of the method if yo can fix it please..

Thanks.

**Comment by hbto** [comment]
@nhomar 

I will

**Comment by hbto** [comment]
@nhomar 

_fix__fixing_method_name_on_product_unique_serial_module_by_hbto_ _pull_request__13_ _vauxoo_stock-logistics-workflow

**Pull request merged**
