### PR TITLE
8.0 review product unique serial osval

### PR DESCRIPTION
**Pull request by osvalr**
This PR gets product_unique_serial and stock_no_negative updated according with OCA guidelines but no API 8.0 yet!, and is the result from details asked by https://github.com/OCA/stock-logistics-workflow/pull/64#issuecomment-145954028 points 1 and 2 are ready, 3rd is pending, and the discuss of 4th pt. is in https://github.com/OCA/stock-logistics-workflow/pull/64 itself. 

Take in count that the current OCA PR (pointed before) is running over 8.0 branch.

@moylop260 and @nhomar let me know your comments about it

### CODE REVIEW

**Comment by moylop260** [comment]
Please review travis result

**Comment by osvalr** [comment]
Hi @moylop260, now this error show up [`travis-ci@84327026`](https://travis-ci.org/Vauxoo/stock-logistics-workflow/jobs/84327026#L170)

**Comment by moylop260** [comment]
@karenkawaii
Me ayudas a estandarizar el .travis.yml de este proyecto please

**Comment by KarenKawaii** [comment]
Ok I'll working on it. Please be patient.

**Comment by osvalr** [comment]
I think this is not valid anymore, im closing it

**Pull request closed without merging**
