### PR TITLE
[MERGE] Update branch from OCA:11.0

### PR DESCRIPTION
**Pull request by luiseevaquer**

### CODE REVIEW

**Comment by luiseevaquer** [comment]
Hi @moylop260 

Please, Can you review this PR?

**Review by luisg123v — APPROVED** [review]

**Comment by moylop260** [comment]
Updated using:

```bash
git checkout -b 11.0 --track vauxoo/11.0
git reset --hard vauxoo/11.0
git pull oca 11.0
git push vauxoo 11.0
```

cc @hugho-ad

**Comment by hugho-ad** [comment]
image

**Comment by moylop260** [comment]
@hugho-ad 
I just have updated this repository.

My script is just a "FYI" for other cases.

Nothing to do here for now.

Note: Before to use the remote from my script, you need define it.

Regards!

**Pull request closed without merging**
